### PR TITLE
Sofle-Pico-Choc Pull Req to main repo

### PR DESCRIPTION
**Pull request by TheWerle**
I think this is ready to be pushed over to the main repo, but haven't ever done this on Github

### CODE REVIEW

**Comment by JellyTitan** [comment]
Exciting! I pulled local and started poking around. 
Can the `Sofle_Chico*` folders be removed?
Are there supporting docs? I'd like to rtm as I look through the schematics/pcb and compare.
Have you produced an MX variant? (If not yet, I'd be delighted to order those and try it out).

image

**Comment by TheWerle** [comment]
Within the MX branch the original Pico folder is the back conversion.  

I'll nuke the Chico folder, I'd hoped to leave the "Chico_Panel" files in my branch but just skip merging, since that was my prototype as-built.

I haven't ordered any boards for either of these files, I figured we'd wait until you or another volunteer gave it at least a cursory review in case I missed something obvious, particularly in case I somehow messed up footprint replacement or something.  Always good to have fresh eyes that will distinguish between forest/trees.  

If you wanna go halvsies again on an MX order I'd be down.

**Comment by JellyTitan** [comment]
Looking great!

Can you run the "Cleanup tracks and vias"? It looks like there's some cruft floating around. 

Screenshot 2024-06-02 at 4 53 44 PM

I did see a few gaps that could be aligned:
Screenshot 2024-06-02 at 4 52 51 PM

Screenshot 2024-06-02 at 4 52 54 PM

There seems to be an 'adapter' folder in the gerber folder? 

image

Since the Choc and MX would both be adding handedness via pin, I think they should go in as the same PR. Can you dump the MX branch with your variant into this PR?

Otherwise - I didn't see any glaring mistakes, so I'd be comfortable ordering the next batch of Choc/MX.

Can you add a zipped set of Gerbers to the Gerbers/current build folder, and move Sofle_Pico_v3.5.4_1-13-24.zip over to legacy build?

Are there updated supporting docs for the new components?

**Comment by JellyTitan** [comment]
> leave the "Chico_Panel" files in my branch but just skip merging, since that was my prototype as-built.

I was giving this some thought, and I realized that if your new to `git`, this might be a bit overwhelming. Here's a quick write up. (Hopefully helpful?)

Regarding the keeping of files - the quick easy way is to create a new branch. Whatever is in the branch your on when you create a new branch will be copied to the new branch. For example:

On your local machine, switch to main
`git checkout main`
Create the new branch
`git branch chico-panel`
Switch to the new branch, verify that what you want is there. (I don't think this is necessary)
`git checkout chico-panel`
Push it up to your repo
`git push origin chico-panel`
At this point, it should appear in the github dropdown:
image

On your local, you can switch back to main
`git checkout main`
Delete the directory
`rm -r Sofle_Chico_Panel` 
Commit the file removal
`git add Sofle_Chico_Panel`
`git commit -m "Sofle_Chico_Panel removal"
Push it up to main
`git push origin main`

Since the PR in this repo is based on branch `main` in your repo, those changes will automatically appear in this PR.

**Comment by TheWerle** [comment]
> > leave the "Chico_Panel" files in my branch but just skip merging, since that was my prototype as-built.
> 
> I was giving this some thought, and I realized that if your new to `git`, this might be a bit overwhelming. Here's a quick write up. (Hopefully helpful?)
> 
> Regarding the keeping of files - the quick easy way is to create a new branch. Whatever is in the branch your on when you create a new branch will be copied to the new branch. For example:
> 
> On your local machine, switch to main `git checkout main` Create the new branch `git branch chico-panel` Switch to the new branch, verify that what you want is there. (I don't think this is necessary) `git checkout chico-panel` Push it up to your repo `git push origin chico-panel` At this point, it should appear in the github dropdown: image
> 
> On your local, you can switch back to main `git checkout main` Delete the directory `rm -r Sofle_Chico_Panel` Commit the file removal `git add Sofle_Chico_Panel` `git commit -m "Sofle_Chico_Panel removal" Push it up to main `git push origin main`
> 
> Since the PR in this repo is based on branch `main` in your repo, those changes will automatically appear in this PR.

Hoping to get to this sometime this weekend. Sorry for delays.

**Comment by JellyTitan** [comment]
Closing this PR as no longer needed - this code was merged in https://github.com/JellyTitan/Sofle-Pico/pull/34

**Comment by JellyTitan** [comment]
Closing this PR as no longer needed - this code was merged in https://github.com/JellyTitan/Sofle-Pico/pull/34

**Pull request closed without merging**
